### ISSUE TITLE
Error: Plugin not found

### ISSUE THREAD

**Issue by economoser** [mcaceresb/stata-gtools#10]
I get the following error when trying to use gtools' -gcollapse- command:
file env_set_macosx.plugin not found
(error occurred while loading gcollapse.ado)
r(601);

**Simple example re-producing the error:**
. ado uninstall gtools

package gtools from https://raw.githubusercontent.com/mcaceresb/stata-gtools/master/build
      ^

(package uninstalled)

. net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/master/build/)
checking gtools consistency and verifying not already installed...
installing into /Users/USER/Library/Application Support/Stata/ado/plus/...
installation complete.

. sysuse auto
(1978 Automobile Data)

. gcollapse (mean) price, by(make)
file env_set_macosx.plugin not found
(error occurred while loading gcollapse.ado)
r(601);

**Comment by mcaceresb** [comment]
Ate you on OSX?

**Comment by economoser** [comment]
I am on a 2016 MacBook with OSX (macOS Sierra). Just saw that you mention the compatibility issue in your README -- sorry for overlooking this. I ran the gtools package on a Unix-based server the other day and it worked great.

**Comment by mcaceresb** [comment]
No worries. I should be more explicit about if you didn't notice. I'll open up an issue about it.

I don't have a Mac and have failed to install it on a virtual machine, so an OSX version is on hold for now.
