### ISSUE TITLE
variable X already defined

### ISSUE THREAD

**Issue by economoser** [mcaceresb/stata-gtools#12]
I discovered that -gcollapse- produces an error when collapsing a variable into a target name that is identical to a variable name that exists pre-collapse. It is easy enough to circumvent, but might be fixed without much trouble? This caused me a bit of a headache trying to troubleshoot, since that behavior of -gcollapse- was not obvious to me.

See minimal working example as follows:

* use -gcollapse- with error:
. sysuse auto, clear
(1978 Automobile Data)

. gen price2=price

. gcollapse price=price2, by(make)
variable price already defined
r(110);

* use -collapse- without error:
. sysuse auto, clear
(1978 Automobile Data)

. gen price2=price

. collapse price=price2, by(make)

**Comment by mcaceresb** [comment]
Can you try the latest version in the development branch? It should be fixed.

```stata
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
```
