### ISSUE TITLE
file gtools_windows_legacy.plugin not found

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#15]
Hi Mauricio,

I just updated gtools and got an error that got me a bit confused (nothing else has changed on my system:

```
. gcollapse (sum) price, by(turn)
file gtools_windows_legacy.plugin not found
```

I'm running Windows 10 and Stata 14.2. The string reported by `which gtools` is this:

```
*! version 0.6.16 13Sep2017 Mauricio Caceres Bravo, mauricio.caceres.bravo@gmail.com
```

**Comment by mcaceresb** [comment]
This should be fixed in the dev branch. Let me know if you keep having any problems. I inadvertently introduced this error when fixing https://github.com/mcaceresb/stata-gtools/issues/15

**Comment by sergiocorreia** [comment]
Thanks, working now!
