### ISSUE TITLE
file gtools_windows_legacy.plugin not found

### ISSUE THREAD

**Issue by fbelotti** [mcaceresb/stata-gtools#16]
Hi Mauricio,

I just installed the gtools package on Stata 14.1 running on Win Server 2012 R2 but I got the following error which seems to be the same reported here https://github.com/mcaceresb/stata-gtools/issues/15.

. gcollapse (mean) price, by(foreign)
file gtools_windows_legacy.plugin not found
(error occurred while loading gcollapse.ado)

. which gtools
c:\ado\plus\g\gtools.ado
*! version 0.6.16 13Sep2017 Mauricio Caceres Bravo, mauricio.caceres.bravo@gmail.com
*! Program for managing the gtools package installation

Do you have any hint?

Many thanks,
Federico

**Comment by mcaceresb** [comment]
This is fixed in 0.6.17+; see https://github.com/mcaceresb/stata-gtools/issues/15

I will be merging a number of bug fixes and features to the master branch in the coming days. Apologies for the issue.

**Comment by fbelotti** [comment]
Ok. I thought that you already merged the fix to the master branch. I just upgraded the package to the last develop branch and it works nicely.

Thanks again.
Best,
Federico
