### ISSUE TITLE
Links from help file

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#17]
Just a minor thing but might be useful:

Sometimes I forget what specific commands are available on gtools, so it would be useful to have such a list within -gtools.sthlp-. Thus, if anyone runs `h gtools` they can then click on the specific command he is interested in.

**Comment by mcaceresb** [comment]
I added this; I forgot to update the version number, so you might need to uninstall and reinstall to see.

**Comment by sergiocorreia** [comment]
Cool, I got it on my side!

Thanks!
