### ISSUE TITLE
(possible suggestion) Speed up gisid if the dataset is already sorted

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#21]
If the dataset is already sorted by the variables (as it often is), we can take advantage of this.

For instance, in the case below, it was 3x faster (0.8s vs 2.5s) to generate ok, run assert, and drop it, than to run gisid (2.5). The other alternatives were way slower of course (12s for fisid and 1m for isid):

```stata
cls
clear
set obs 10000000
gen long id = (_n / 10)
bys id: gen double t = _n * 1000
sort id t

set rmsg on

*isid id t
fisid id t
gisid id t

by id t: gen byte ok = _n == 1
assert ok
drop ok
```

A quick way to implement this in an ado would be to add something like this at the beginning of the ado:

```stata
if ("`: sortedby'" == "`varlist'") {
	tempvar ok
	by id t: gen byte `ok' = _n == 1
	cou if !ok
	drop `ok'
	if (r(N)) {
		di "not unique"
		exit 459
	}
}
```

That said, I'm not entirely sure it will be widely useful. If `t` is instead a byte variable, most of the advantage is gone. Also, it would need to support if/in.

**Comment by mcaceresb** [comment]
The speed gains are not there for me, so I can't assume it will be faster in every version of Stata.

I have an internal check to see if it's sorted for hashsort. Basically a recursive call to

```
for (i = start + 1; i < end; i++)
    if ( comp(i - 1, i) > 0 ) return (0);
return (1);
```

So if the previous element is  greater, it is not sorted. If all elements are s.t. `i - 1 <= i` then it is sorted. I think I can modify it for isid:
```
for (i = start + 1; i < end; i++)
    if ( (rc = comp(i, i - 1)) <=  0 ) return (rc);
return (1);
```

If 1 then this is an id because every element is such that `i > i - 1`; if 0 then this is not an id because there exists an element such that `i == i - 1`. If -1 then this is not sorted and I can proceed with the hash normally.

**Comment by mcaceresb** [comment]
I just tried a version on this on Linux and had a 5x speedup. I'll write tests to make sure I'm not misidentifying when a set of variable is or not an id

**Comment by sergiocorreia** [comment]
Cool! Let me know if you want me to run any benchmark,

**Comment by mcaceresb** [comment]
I haven't pushed. I need to write tests to make sure I haven't mis-coded anything. I'll write those tomo and let you know to see if the speedup holds on your end.

**Comment by mcaceresb** [comment]
I have added the changes. Let me know how it benchmarks.

**Comment by sergiocorreia** [comment]
Yep, much faster!

`gisid` is now at half the speed of the `gen + assert` trick (which is 3x faster than `gisid` on the master branch, which is 4x faster than `fisid`, which is 5-10x faster than isid)

On the past I rarely used `isid` because it was slow, so the new way of doing it is a game changer in my opinion., as I can check almost instantly if I have unique IDs or not.
