### ISSUE TITLE
a bug in hashsort?

### ISSUE THREAD

**Issue by ractingmatrix** [mcaceresb/stata-gtools#26]
Hi

Thanks for the great work on gtools. It seems to me there may be a bug in hashsort. Please refer to the code below:

××××××××××××××××××××××××××××××

clear *
set obs 100
gen id1=round(_n,5)
gen id2=round(_n,15)

hashsort id1 -id2
by id1: gen value=_n //caused error

gsort id1 -id2
by id1: gen value=_n //caused no error

××××××××××××××××××××××××××××××

Grateful for advice.
DW

**Comment by mcaceresb** [comment]
Thanks! A fix is in develop (gtools 0.9.4). Please confirm the fix and I will merge to master.

**Comment by ractingmatrix** [comment]
thanks for the fix. it works well.
