### ISSUE TITLE
bug in gcollapse?

### ISSUE THREAD

**Issue by ractingmatrix** [mcaceresb/stata-gtools#29]
Please refer to the attached pictures (sorry I have difficulties reproducing the data). In my data there is a variable "oobbu" whose maximum value is 3231, as indicated in the picture.  after gcollapse (firstnm), the maximum of "oobbu" becomes 2.14e+09, which is wrong. 

This issue seems to be solved if I save the data in memory first, followed by "use XXX, clear" , and then do the gcollapse again (the second picture).

![sample_nosave](https://user-images.githubusercontent.com/24869490/32696607-8868674e-c7b7-11e7-9884-86445f04a1ad.png)
![sample_save](https://user-images.githubusercontent.com/24869490/32696608-8b2fc828-c7b7-11e7-9158-4b2189324291.png)

**Comment by mcaceresb** [comment]
1. Is it the only one that is off, or are the other `firstnm` and `lastnm` also off?
   It would be helpful if you ran it with the option `verbose` and posted that output,
   along with the output of `su` pre and post `gcollapse`

2. Can you post the output of

```stata
use ${sample}_temp, clear
su id
su id if id < r(mean)
keep if _n <= r(N)

gegen f1 = firstnm(oobbu), by(id date)
gcollapse (firstnm) f2 = oobbu, by(id date) merge
return list
su f1 f2
```

**Comment by ractingmatrix** [comment]
pls see the attached log.
[mylog.txt](https://github.com/mcaceresb/stata-gtools/files/1464729/mylog.txt)

re 1, oobu, oobe, p25, p75, and pc all seem off, as indicated in the log. 

thanks for looking into.

**Comment by mcaceresb** [comment]
Ok, I'm 99% sure I know where the problem is (just not what it is yet). Can you run the first collapse with both `verbose` and `forcemem` and post the results? If that looks fine, then the problem is definitely with the I/O code.

**Comment by ractingmatrix** [comment]
here you go:
[mylog.txt](https://github.com/mcaceresb/stata-gtools/files/1464756/mylog.txt)

**Comment by mcaceresb** [comment]
Can you put this ado file in your working directory: [gcollapse_debug.ado](https://github.com/mcaceresb/stata-gtools/files/1464787/gcollapse_debug.txt) and run "gcollapse_debug" instead of "gcollapse" with the options "verbose" and "foreio" (instead of "forcemem"). (You may have to rename the file from gcollapse_debug.txt to gcollapse_debug.ado).

After the run, also include the output of "mata: __gtools_data[1::10, 1::5]"

**Comment by ractingmatrix** [comment]
here u go:
[mylog.txt](https://github.com/mcaceresb/stata-gtools/files/1464838/mylog.txt)

**Comment by mcaceresb** [comment]
Thanks! I was able to reproduce the error and am debugging. Please run gcollapse with the option `forcemem` until I mark this as solved.

**Comment by ractingmatrix** [comment]
just run my work. the fix is good. thanks.
