### ISSUE TITLE
gegen total does not parse "exp" correctly

### ISSUE THREAD

**Issue by Danferno** [mcaceresb/stata-gtools#33]
The default Stata total() allows for an expression between the parentheses, which is something more convenient than if-conditions (e.g. you want to take the total over certain observations, but list the value in all observations). De help file for gegen suggests this is also possible with gtools, but instead I get 
`sum(varlist) must call a numeric variable list.`

when asking 

`bysort iri_key: gegen firstYearRev 	= total(dollar * inFirstYear)`

**Comment by mcaceresb** [comment]
I see. The problem is that you can also specify a varlist, and I defaulted to trying to parse the expression as a varlist first and an expression second. I'll reverse it, and default to checking for an expression first and a varlist second (since egen does not allow a varlist anyway).
