### ISSUE TITLE
"gtools, dependencies" not working with spaces in filepath

### ISSUE THREAD

**Issue by jfasonntag** [mcaceresb/stata-gtools#36]
Hi!

I noticed that "gtools, dependencies" threw an error at me for not finding the spookyhash.dll in my ado folder despite it being there.

After inspection of gtools.ado I found that the issue was caused by not enclosing the filepaths in additional quotation marks. If your ado-path contains spaces (like in my case) then this will cause problems. I fixed it by enclosing the filepaths on lines 25, 26 and 65 in quotes.

No idea if that solution is windows-sepecific, but maybe its worth including that in the next update.

Thanks a lot for writing this great plugin, this is extremely useful!

**Comment by mcaceresb** [comment]
Line 65 shouldn't make a difference. Line 41 is also possible problem, however (as are 25-26). Thanks for pointing it out!
