### ISSUE TITLE
gcollapse: Support for rawsum / selective weights in general

### ISSUE THREAD

**Issue by Danferno** [mcaceresb/stata-gtools#37]
Hi

Are there plans to support gcollapse (rawsum), or more generally allow for certain operation to be weighted whilst others are not? I frequently run into situations where I'd like to calculate a weighted mean, but an unweighted sum, which at the moment means I'm limited to using collapse in those situations (or spend extra time coding workarounds).

By the way, thanks for this great suite of tools, I use it regularly and it has made significant improvements to the runtime of some of my programs.

**Comment by mcaceresb** [comment]
Mmm... Yes, I will implement rawsum. At this point, it bothers me that I have to keep noting "rawsum" is not implemented. It will only take a few minutes, but testing might take a bit longer.

I agree it's a good idea to add "rawstat" so you can pass a list of targets, for which weights will be ignored. I won't make it too smart, so it will be slightly slower than regular gcollapse, but it should certainly be much faster than doing it two gcollapses.

It won't take very long to implement either, but I'm rather busy this week. Perhaps after the weekend or during the next. Cheers!

**Comment by Danferno** [comment]
Great!

**Comment by sergiocorreia** [comment]
I think having a general rawstat is a great idea, but I'm wondering about a corner case:

```stata
sysuse auto
collapse (sum) turn (rawsum) rawturn=turn [fw=foreign]
list
```

You'll notice that sum and rawsum give the same result, because rawsum also ignores cases where foreign==0 (i.e. zero weights).

It's something you won't expect unless you know the details about the implementation (that on an early step we exclude obs. where the weights are zero), so it's a bit troublesome (but also a problem of collapse in general)

**Comment by sergiocorreia** [comment]
Agree with you. Did a quick commit to ftools that just does it the easy way. I think just adding a warning on the help file will suffice.

**Comment by mcaceresb** [comment]
Nice; unfortunately for me the way I wrote gcollapse's internals requires a different set of functions for each of these things. Mainly copy/paste with small tweaks, but still.
