### ISSUE TITLE
`gegen group` misc issues

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#4]
A few issues with `gegen`:

- It doesn't seem to respect the order of the data. EG:

```stata
sysuse auto, clear
egen id1 = group(turn trunk)
fegen id2 = group(turn trunk)
gegen id3 = group(turn trunk)

assert id1==id2
assert id1==id3
```

The last command fails as the IDs are not the same

- It doesn't warn for incorrect options:

```stata
gegen id = group(turn) , wrongoption
```

Should give a warning that an incorrect option was used.

**Comment by mcaceresb** [comment]
I note in the README that gegen does not respect group order; perhaps I should change the function name since you find it misleading? (I'll fix the wrong option bug)

**Comment by sergiocorreia** [comment]
Another problem is that the new IDs seem to have holes:

```stata
sysuse auto, clear
gegen id = group(turn) in 20/30
tab id
```

(groups 1-4, 6, 8, etc. are missing)

**Comment by mcaceresb** [comment]
I see. This is not a but per se, though, since all the groups are there and the ID is unique, but I agree that coupled with the order issue it makes the ID rather confusing.

**Comment by mcaceresb** [comment]
The IDs should no longer have have holes, and extraneous options now give an error. See `0.6.10` (master branch). However, the order of the IDs is pending a future release. I am opening a new issue for that. (See issue https://github.com/mcaceresb/stata-gtools/issues/6).
