### ISSUE TITLE
nansum option in gcollapse?

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#46]
In some large datasets I often want to do `collapse (sum) var1-var1000 ...`, but if a variable is always missing within a group, keep the sum as missing instead of zero:

```stata

clear
input byte(id x)
1 .
1 .
2 4
2 6
end

preserve
collapse (sum) x, by(id) fast
list
restore

preserve
fcollapse (nansum) x, by(id) fast
list
restore
```

Is there a way to do something like this with `gcollapse`? Other statistics (mean, etc.) already do this, it's only sum that causes problems.

Thanks!
Sergio

**Comment by mcaceresb** [comment]
See option `missing`. Do you think it ought to be a sepparate stat?

**Comment by sergiocorreia** [comment]
Cool! The only case where it would be useful as a separate stat is if you want to keep missings for some variables and convert them to zero for others.

It's not my use case, but it can certainly happen.

Thanks!

**Comment by mcaceresb** [comment]
I actually hadn't noticed, but rawsum leaves a missing value if all are missing... I guess that ought to be a bug, and there should be `nansum` and `rawnansum` (`nanrawsum`?)

**Comment by sergiocorreia** [comment]
Yep, I hadn't spotted that bug either (otherwise I would have taken advantage of it).
Both nansum and rawnansum would be useful, although I would only include them if the coding involved is not too much

Thanks!
Sergio
