### ISSUE TITLE
gegen tag treatment of missing

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#5]
```stata
sysuse auto, clear
egen t1 = tag(rep)
gegen t2 = tag(rep)
li rep t? if t1!=t2
assert t1==t2
```

The assertion fails because `gegen` tags missing values of rep, while `egen` doesn't.

From the help files: "The result will be 1 if the observation is tagged and never missing, and 0 otherwise", so I think MVs should have a tag of zero unless the `missing` option is included.

**Comment by mcaceresb** [comment]
This should be fixed in version `0.6.9` (see develop branch).
