### ISSUE TITLE
gstat winsor segfaults when the upper cut is 100 and the data is not sorted

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#51]
If the data is unsorted, winsorizing below (e.g. with `cut(10 100)`) can cause a segfault.

Also related, if one of the cuts is missing, I'm not sure what's the output. EG: `cut(10 .)`

Code sample:

```stata
* Create data
clear
input int x long(y z)
 1 357 554
 2 400 955
 3 689 895
 4 559 956
 5 574 503
 6 207 619
 7  28 321
 8 688 123
 9 469 445
10 207 554
11   3  18
12  13 912
13 420 776
14 616 616
15 894 132
16 410 647
17 260 730
18  26 446
19 107   7
20 366 664
end

gstats winsor x, suffix(_1) cut(0 80) // ok
gstats winsor x, suffix(_2) cut(20 100) // ok
gstats winsor x, suffix(_3) cut(20 .) // wrong?
gstats winsor x, suffix(_4) cut(0 100) // ok

sort y

gstats winsor x, suffix(_5) cut(0 100) // segfault
gstats winsor x, suffix(_6) cut(20 100) // segfault
```

**Version info**
 - OS: Windows 10 (problem also happens on Linux)
- Stata version: Stata 14.2
 - Version: version 1.2.0 16Dec2018 (latest develop build)
- Note: not run with `verbose` option as I can't see what happens after the segfault (I could try logging though)

**Comment by mcaceresb** [comment]
@sergiocorreia Let me know if the fix in develop is working for you.

**Comment by sergiocorreia** [comment]
Seems to be working now, thanks!
