### ISSUE TITLE
Error  code "<istmt>:  3301  subscript invalid r(3301)" when using greshape spread or greshape wide

### ISSUE THREAD

**Issue by elektrotiko** [mcaceresb/stata-gtools#54]
Hello

I get error code <istmt>:  3301  subscript invalid r(3301)" whenever trying to greshape spread or greshape wide the below dataset. Please note that Stata's reshape wide command works well if used at this stage.

What is wrong or what am I missing here?

Thanks in advance!

. dataex

----------------------- copy starting from the next line -----------------------
[CODE]
* Example generated by -dataex-. To install: ssc install dataex
clear
input float community int year str16 variable float values
 1 2009 "sales"     14
 1 2017 "sales"     19
 2 2009 "sales"    7.8
 2 2017 "sales"    7.8
 3 2009 "sales"   49.8
 3 2017 "sales"   37.4
 4 2009 "sales"  872.4
 4 2017 "sales"  556.4
 5 2009 "sales"  180.6
 5 2017 "sales"  124.4
 6 2009 "sales"   20.4
 6 2017 "sales"   11.6
 7 2009 "sales"     21
 7 2017 "sales"    9.4
 8 2009 "sales"   59.2
 8 2017 "sales"   57.6
 9 2009 "sales"     55
 9 2017 "sales"   44.4
10 2009 "sales"   26.6
10 2017 "sales"     13
11 2009 "sales"     34
11 2017 "sales"   24.6
12 2009 "sales"    7.8
12 2017 "sales"   10.2
13 2009 "sales"      9
13 2017 "sales"    5.4
14 2009 "sales"   21.6
14 2017 "sales"   13.8
15 2009 "sales"     23
15 2017 "sales"   21.4
16 2009 "sales"  520.6
16 2017 "sales"  367.2
17 2009 "sales"   49.4
17 2017 "sales"   20.6
18 2009 "sales"   75.8
18 2017 "sales"   28.2
19 2009 "sales"  175.2
19 2017 "sales"  120.2
20 2009 "sales"   35.2
20 2017 "sales"   29.4
21 2009 "sales"   20.8
21 2017 "sales"   16.2
22 2009 "sales"   27.8
22 2017 "sales"   31.2
23 2009 "sales"   83.8
23 2017 "sales"     41
24 2009 "sales"   46.2
24 2017 "sales"   29.4
25 2009 "sales"   36.8
25 2017 "sales"     19
26 2009 "sales"   20.4
26 2017 "sales"   12.2
27 2009 "sales"      9
27 2017 "sales"    6.4
28 2009 "sales" 1965.2
28 2017 "sales" 1227.2
29 2009 "sales"   25.2
29 2017 "sales"   19.6
30 2009 "sales"   42.4
30 2017 "sales"   34.2
31 2009 "sales"   20.6
31 2017 "sales"     18
32 2009 "sales"  176.8
32 2017 "sales"  118.2
33 2009 "sales"   11.4
33 2017 "sales"    6.8
34 2009 "sales"  113.4
34 2017 "sales"   72.8
35 2009 "sales"   10.8
35 2017 "sales"    9.2
36 2009 "sales"   21.6
36 2017 "sales"   13.6
end
[/CODE]
------------------ copy up to and including the previous line ------------------

**Comment by mcaceresb** [comment]
What is the command that gives you an error? This is working for me:

```
greshape spread values, by(community) keys(variable year)
```

**Comment by elektrotiko** [comment]
Dear Mauricio

You solved my problem!

Have a great one!

P.S. Thanks for the great package

**Comment by mcaceresb** [comment]
Happy that it's working for you! Maybe there was a syntax error but I know that `greshape` uses mata in several places under the hood and I try to give useful error messages, so I'd be curious to see why your previous command failed.

**Comment by elektrotiko** [comment]
Dear Mauricio

I was literally following the manual on your Gtools website and ran this code: greshape spread values, keys(variable), which gave me the above error.

**Comment by mcaceresb** [comment]
Thank you; I get the same error. This is a parsing bug in `greshape`. I will push a fix as soon as I can.
