### ISSUE TITLE
A "separate" option for greshape spread

### ISSUE THREAD

**Issue by elektrotiko** [mcaceresb/stata-gtools#63]
**What would you like gtools to add or change (and why)?**
I would like to see an added option for greshape spread that is similar to Stata's official "separate" see `(help separate in Stata)`. The problem with greshape spread is that it automatically takes the string value of the "keys" variable and makes strtoname conversion in order to adapt it to Statas permitted formats for variable names. When we instead use the command "separate", for instance separate COUNT, by(Aliases) gen(Alias_), we get to choose the stub for our new variable names, which here is "Alias_". The latter is important since we usually want to retain the given string value as the variabel label of the new variable created by greshape spread. The bug right now is that pure string variables with "strange" characters cause this error

`j defines non-unique or invalid names
r(198);`

**Comment by mcaceresb** [comment]
greshape should preserve the original names as labels. Can you please run

```
gtools
```

and then post an example that produces the error you mean? I looked at separate's help page and did not quite see what you meant.

**Comment by elektrotiko** [comment]
`
*! version 1.5.3 04Apr2019 Mauricio Caceres Bravo, mauricio.caceres.bravo@gmail.com
*! Program for managing the gtools package installation
(note: gtools_plugin v1.5.0 successfully loaded)
r; t=0.01 9:56:52
`
Let me put it another way to make it more clear. Currently the problem with `greshape spread` is that it creates new variables from the values of the variable specified in the options `key(keyvariable)`. New variable names are not `keyvariable1 keyvariable2 etc`, which is unfortunate. What we rather need is to be able to use our own "stubs" to new variable names to avoid the problem with current greshape spread in cases where our keys variable is string and has long string values. This causes Stata to stop due to illegal variable names.

**Comment by mcaceresb** [comment]
See branch `develop`; will hit master soon. You can specify custom stub names via `prefix()` in greshape wide and greshape gather:

```stata
webuse reshape1, clear
qui greshape long inc ue, i(id) keys(year)
qui greshape wide inc ue, i(id) keys(year) prefix(year@income #stub#)

webuse reshape1, clear
qui greshape gather inc* ue*, values(values) key(varaible)
qui greshape spread values, key(varaible) prefix(foo_@_bar_#stub#)
```
