### ISSUE TITLE
gegen rank vs. egen rank

### ISSUE THREAD

**Issue by economoser** [mcaceresb/stata-gtools#68]
It seems that, oddly, the -rank- subcommand of -gegen- does not support a by-option, while the original -egen- command does. Maybe a bug? See example below:

```
. bys year: gegen inc_rank = rank(inc)
by: prefix not allowed with rank
r(198); t=0.02 9:18:35

. bys year: egen inc_rank = rank(inc)
(9925 missing values generated)
r; t=0.10 9:18:39
```

**Comment by mcaceresb** [comment]
This is not so much of a bug as maybe a design flaw. I purposely disallowed that in case the user tried to pass something that is allowed with by but that I wouldn't account for... However, in this case I force the input to be a single variable, so it might be OK.

I'l _probably_ allow the by prefix in the next release. In the meantime you can comment out lines 152 to 155 in gegen.ado as a quickfix (i.e. [these lines](https://github.com/mcaceresb/stata-gtools/blob/master/src/ado/gegen.ado#L146-L149)).
