### ISSUE TITLE
Feature request - greshape wide - separate

### ISSUE THREAD

**Issue by elektrotiko** [mcaceresb/stata-gtools#69]
Hi

There is a very slow command in Stata named "separate". What is does is creating new variables containing values from varname.

It would be great to have a similar option for greshape wide , separate that does the same thing, i.e. when reshaping to wide also taking the string value from previous variable and making in the variable label of the new variables in question.

Is that possible?

P.S. Note that some string [aliases] may contain leading or trailing blanks, which would require trimming the string before making the new variable labels for wide-reshaped ones.

Regards

**Comment by mcaceresb** [comment]
So, th behavior of separate in general seems to me quite different to reshape.

You just mean the part where it appends to the variable label a note saying "variable = value"?

**Comment by elektrotiko** [comment]
Yes, that correct. I want to be able to greshape wide and set new variable labels from original string values.

**Comment by mcaceresb** [comment]
This is now available. To imitate `separate` labeling you can do:

```stata
sysuse auto, clear
local labelformat labelformat(#stubname#, #keyname# == #keyvaluelabel#)
greshape wide mpg, by(make) key(foreign) `labelformat'
desc mpg*
```

However, you can use any combination of placeholders. For instance,

```
sysuse auto, clear
local labelformat labelf(#stublabel#; #keylabel# == #keyvaluelabel#)
greshape wide mpg, by(make) key(foreign) `labelformat'
desc mpg*
```

Placeholders available are `#stubname#`, `#stublabel#`, `#keyname#`, `#keylabel#`, `#keyvalue#`, and `#keyvaluelabel#`.
