### ISSUE TITLE
Error compiling Gtools

### ISSUE THREAD

**Issue by glennmagerman** [mcaceresb/stata-gtools#71]
Hi, thanks a lot for this suite of commands!

I'm trying to compile the plugins on a Mac OS X Catalina system as described [here](https://gtools.readthedocs.io/en/latest/compiling/index.html).
However, I keep running into the same error: 

```
test(failed): checks_gregress, oncollision(error)

WARNING: 10:41:04 12 Sep 2020
tests ran with non-0 exit status

tests ran but Stata gave error code r(199)
```

Any idea what the issue is and/or how to solve it?

**Comment by mcaceresb** [comment]
What do you get if you just run `checks_gregress`?

**Comment by glennmagerman** [comment]
I cannot find checks_gregress, but i do find a series of test_*.do in src/test.
These all execute flawlessly.

**Comment by mcaceresb** [comment]
I see. I think this:

- Run `src/gtools_tests.do` _wihout_ the last line

- Run `src/test_gregress.do`

- Run `checks_gregress`

**Comment by glennmagerman** [comment]
sorry for being slow:
- I can find `src/test/gtools_tests.do` and `build/gtools_tests.do`. Which one to use?
- Then, given the right do-file, which last line to drop? in  src/test/gtools_tests.do, the last 2 lines are

```
if ( `"`0'"' == "" ) local 0 dependencies basic_checks comparisons switches bench_test
main, `0'
```
- I cannot find checks_gregress.do

**Comment by mcaceresb** [comment]
- The former is fine.

- Don't run `main`.

- `checks_gregress` is a program, not a do file.

**Comment by glennmagerman** [comment]
thanks - if I do that, commenting out `main` leads the do-file to run in a split second, probably skipping most content.
not sure where to find or how to call checks_gregress then?

**Comment by mcaceresb** [comment]
In the same Stata session that you run the other files, type checks_gregress into the Stata console and press enter.

**Comment by glennmagerman** [comment]
That returns the following error `command checks_gregress is unrecognized`

**Comment by mcaceresb** [comment]
`checks_gregress` is defined in `src/test/test_gregress.do`. If you ran that in the same session then it's odd that it wouldn't be recognized.

I made a file [here](https://raw.githubusercontent.com/mcaceresb/stata-gtools/3aef00ce59b72eaaf86fa82121aa68db6a00c59f/src/github-issues/71/test.do) so you can test out what I mean you to run. Let me know the error you get (or you can post the log from your run).

**Comment by glennmagerman** [comment]
Thanks a lot - your file looks different from the one I have in src/test, but yours runs without any error!
Weird, since I upgraded gtools today + pulled the gtools compile folder from GitHub also today...
But this seems to work... Is there anything else I need to do for the compiled version to run (i.e. how does Stata know which version to run?)

**Comment by mcaceresb** [comment]
Mmm. You need to install the version you built. You can manually replace the plugin files or install from your local build folder (if doing the latter I would uninstall gtools first)

**Comment by glennmagerman** [comment]
awesome, thanks a lot!
