### ISSUE TITLE
gtools not installing on macos Stata 16

### ISSUE THREAD

**Issue by sushilmathew93** [mcaceresb/stata-gtools#77]
**Describe the bug**
- I tried to install gtools using ssc install gtools (just like I do with any other ssc install), but it doesn't get installed, I've pasted my code and output below.

**Code Sample**

```stata
// code snippet
ssc install gtools
```

```stata
// output (or attach a .log file)
I/O error
could not copy http://fmwww.bc.edu/repec/bocode/g/gtools_windows_v2.plugin
(no action taken)
r(691);
```

**Version info**
 - OS: macOS Big Sur 11.4
 - Version: NA

**Comment by mcaceresb** [comment]
@sushilmathew93 Stata version?

**Comment by sushilmathew93** [comment]
16.1

**Comment by sushilmathew93** [comment]
Hi again! I should've probably tried this earlier, but I closed Stata and reopened it and updated it. I'm able to install gtools now!
