### ISSUE TITLE
Problem with -if- condition in several commands

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#78]
**Describe the bug**

If the -if- condition has an open or close parenthesis, gtools (gegen/gdistinct/gunique/etc) returns with error `too few ')' or ']'`

**Code Sample**
Include a code snippet to reproduce the problem; be sure to run the relevant `gtools` program(s) with options `verbose bench(3)`.

These lines trigger the error:

```stata
sysuse auto
gdistinct make if !strpos(make, ")") // fails
gunique make if !strpos(make, ")") // fails
gegen x = group(foreign) if !strpos(make, "x)") // fails
```

Running with verbose:

```stata
. gdistinct make if make!="(", verbose bench(3)
Parsed by variables; .003 seconds
too few ')' or ']'
```

**Version info**
 - OS: Win10[e.g. Windows 10]
 - Version: 1.7.5 18Apr2020

**Comment by mcaceresb** [comment]
@sergiocorreia Ah, this seems to be an issue throughout my entire code pipeline. I'll have to switch up how I'm passing `if` and `in` around in a few places. Thanks for flagging!
