### ISSUE TITLE
Please update the benchmark using Stata 17.

### ISSUE THREAD

**Issue by tatanlabra** [mcaceresb/stata-gtools#79]
Just to validate and adjust the expectations of improvements in newer versions, at least an approx.

**Comment by mcaceresb** [comment]
@tatanlabra I won't do this until I have access to Stata 17. However, I will add a disclaimer the benchmarks (in particular collapse) are presumably dated.

**Comment by tatanlabra** [comment]
I can run the quick benchmarks in 16 and 17, maybe adding box plots from different scenarios, and sharing the results here.

**Comment by mcaceresb** [comment]
@tatanlabra While I appreciate the offer I would rather run the benchmarks myself before updating the README. (I am also curious to test out the faster collapse.) However, you are welcome to post your results here so others might find this thread (only warning is that I manually copy the times to make the plot; I didn't automate that part.)

**Comment by osnofas** [comment]
I can help with Stata 17 benchmarks as well. (Regardless I'll keep using Gtools as the syntax and capabilities are better than Stata's commands!)

**Comment by mcaceresb** [comment]
@tatanlabra @osnofas I finally had occasion to test out Stata's collapse on 17/MP. `collapse` was indeed faster on my quick benchmarks. However, after some probing:

- Single core performance is slower for native collapse.
- In SE native collapse remains slower.
- The speed improvement does not hold for some collapses or machines (on my laptop, even slightly complicated collapses were slower, as were collapses with larger data, e.g. 100M; on the server where I work, however, native collapse was 2x faster across the board).

I resolved to note in the README and the `gcollapse` docs that the native `collapse` in 17/MP is often faster but may also be slower. I think this is  a sensible way to update the  docs (but feel free to add any comments or feedback). Cheers!
