### ISSUE TITLE
-gegen- only provides support for by-able egen functions 

### ISSUE THREAD

**Issue by heidenfahrt** [mcaceresb/stata-gtools#8]
I observe the following behavior of gegen on WIN 7 and Linux:
```

. sysuse auto
(1978 Automobile Data)

. gegen mean=mean(mpg)
-gegen- only provides support for by-able egen functions
r(198);

. by foreign: gegen mean=mean(mpg)
-gegen- only provides support for by-able egen functions
r(198);


```
This also happens with other `gegen` functions.

**Comment by mcaceresb** [comment]
For some reason I had commented out the lines that made `gegen` by-able... I fixed this. I also allow the function to be called without "by" (it now assumes it wants the overall stat). The changes are in the develop branch. When we sort out issue https://github.com/mcaceresb/stata-gtools/issues/9 I will merge to master.
