### ISSUE TITLE
Error trying to copy gtop.sthlp in Stata 14

### ISSUE THREAD

**Issue by bdiazdeastarloa** [mcaceresb/stata-gtools#86]
Hi, 

I get this error when trying to run "gtools, upgrade" in STATA 14:

could not copy https://raw.githubusercontent.com/mcaceresb/stata-gtools/master/build/gtop.sthlp

Running on a MacBook Air.

Thanks!

**Comment by mcaceresb** [comment]
@bdiazdeastarloa Hey! Very sorry for the lag. Can you try `gtools, upgrade branch(develop)`? I've pushed a fix to that branch.

**Comment by mcaceresb** [comment]
This should now be merged in master.

**Comment by bdiazdeastarloa** [comment]
It works now, thanks!
