### ISSUE TITLE
Why does gcollapse fail to load multi-threaded version; using fallback

### ISSUE THREAD

**Issue by felixholub** [mcaceresb/stata-gtools#9]
When I run 
```
sysuse auto
gcollapse mpg, by(foreign) verbose
```
The collapse works but I'm told that 
`note: failed to load multi-threaded version; using fallback`, even though I'm running it with Stata-MP on multicore Linux (and WIN 7, but this is pointed out in TODO). Not sure if a bug or lack of understanding on my site.

**Comment by mcaceresb** [comment]
Whether or not Stata is MP should be irrelevant for this. From a terminal on linux, what is the output of

```bash
ldconfig -p | grep libgomp
echo $LD_LIBRARY_PATH
```

**Comment by heidenfahrt** [comment]
`-bash: ldconfig: command not found`
I would need to contact the system admin (it's a server) in case this is required.

**Comment by mcaceresb** [comment]
Try these:

```bash
locate libgomp
whereis libgomp.so
whereis libgomp.so.1
```

If it exists in your system, it may also be named `libgomp.so.1.0` or `libgomp.so.1.0.0` so try searching for them as well. Let me know if any of these commands fail.

**Comment by heidenfahrt** [comment]
Output of `locate libgomp`
```
/usr/lib/gcc/x86_64-linux-gnu/4.7/libgomp.a
/usr/lib/gcc/x86_64-linux-gnu/4.7/libgomp.so
/usr/lib/gcc/x86_64-linux-gnu/4.7/libgomp.spec
/usr/lib/x86_64-linux-gnu/libgomp.so.1

/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
/usr/share/doc/libgomp1
/usr/share/doc/gcc-4.7-base/test-summaries/libgomp.sum.gz
/var/lib/dpkg/info/libgomp1:amd64.list
/var/lib/dpkg/info/libgomp1:amd64.md5sums
/var/lib/dpkg/info/libgomp1:amd64.postinst
/var/lib/dpkg/info/libgomp1:amd64.postrm
/var/lib/dpkg/info/libgomp1:amd64.shlibs
/var/lib/dpkg/info/libgomp1:amd64.symbols
```
The output of the various `whereis` commands is always empty.

**Comment by mcaceresb** [comment]
I see. Can you try

```bash
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
stata
```

and then, from the stata command prompt,

```stata
sysuse auto
gcollapse mpg, by(foreign) verbose
```

And let me know the output? This may be an issue with stata being unable to find libgomp, which the plugin uses for parallelism. If this works, there may be a simple solution so you don't have to run this every time. Let me know.

**Comment by heidenfahrt** [comment]
Hi Mauricio,
I still get the multi-thread fail output doing as you described.

Am 18.08.2017 um 14:23 schrieb Mauricio Caceres Bravo:

**Comment by mcaceresb** [comment]
Apologies for the tardiness debugging. I just tried this on a fresh Linux install and it worked. I have to assume it has to do with one of the following:
- OS
- Version
- Processor

I will try to replicate your situation more closely. Can you run and paste the output of

```bash
cat /etc/*release*
uname -a
lscpu
```

**Comment by heidenfahrt** [comment]
```
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```
```
3.2.0-4-amd64 #1 SMP Debian 3.2.81-2 x86_64 GNU/Linux
```
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               3300.402
BogoMIPS:              6599.92
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
```

**Comment by mcaceresb** [comment]
I was able to reproduce the bug. It seems it's just a versioning issue, but all the functionality appears to be compatible.

Can you try the latest development branch version? I have added a version of the plugin that uses an older version of libgomp.

```stata
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
sysuse auto
gcollapse mpg, by(foreign) verbose
```

**Comment by mcaceresb** [comment]
Actually, do not use the plugin just yet. It seems there is another problem with using the plugin on an older OS. The hashing function does not actually work and it will cause a segmentation fault (crash).

Integers are fine because they are not hashed, but anything other than integers is causing a crash for me.

**Comment by mcaceresb** [comment]
Can you try again? Latest dev and using `headroom make`? It no longer crashes for me (version `0.6.14`)

```stata
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
sysuse auto
gcollapse mpg, by(headroom make) verbose
```

**Comment by heidenfahrt** [comment]
Now it works indeed! Thanks a lot for the support Mauricio, keep up the great work!

**Comment by mcaceresb** [comment]
By the way, don't update the plugin. I have added new commands and this broke the legacy compatibility I added here. I'm reopening the issue until I figure out a fix for the new commands as well.
