### ISSUE TITLE
gcollapse the first record of a string variable

### ISSUE THREAD

**Issue by jankabatek** [mcaceresb/stata-gtools#98]
Hi Mauricio, awesome work on the package! I wanted to raise one small issue: 
Unlike collapse & fcollapse, gcollapse does not seem to support collapsible strings:

**Code Sample**

```stata
sysuse surface, clear

collapse (first) date, by(latitude)
fcollapse (first) date, by(latitude)
gcollapse (first) date, by(latitude) verbose bench(3)
```

```stata

. sysuse surface, clear
(NOAA sea surface temperature)

. collapse (first) date, by(latitude)

. fcollapse (first) date, by(latitude)

. gcollapse (first) date, by(latitude) verbose bench(3)
'date' found where numeric variable expected
r(7);

```

**Version info**
 - OS: Windows 11]
 - Version: 1.11.8

**Comment by mcaceresb** [comment]
Hi @jankabatek , this is currently an ~intended~ known limitation of gcollapse. See #25 for a discussion. Sorry for the inconvenience! Cheers.

**Comment by jankabatek** [comment]
Ah, I see! Thanks for letting me know.
